<a href="https://colab.research.google.com/github/PDM-15/AML-2026/blob/master/AML_Lab7/Assignment7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data 1

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
import pandas as pd

# Update the path below to match your actual file location
file_path = '/content/drive/My Drive/Dataset/data-1.csv'
# View the first few rows
df = pd.read_csv(file_path)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   offer  Age  online payment  items
0      1   35               0      5
1      1   26               0      4
2      1   41               0      9
3      1   34               0     10
4      1   38               0      3

In [ ]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

X = df

selector = VarianceThreshold(threshold = 0.0)
X_selected = selector.fit_transform(X)

selected_columns = X.columns[selector.get_support()]

print("Selected Features:", list(selected_columns))

Selected Features: ['Age', 'items']

Data 2

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
import pandas as pd

# Update the path below to match your actual file location
file_path = '/content/drive/My Drive/Dataset/data-2.csv'
# View the first few rows
df2 = pd.read_csv(file_path)
df2.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

   referred  repeat  Age  Promoted  items
0         1       0   35         1      5
1         0       0   26         0      4
2         1       0   41         1      9
3         1       1   34         0     10
4         1       0   38         1      3

In [ ]:
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

X = df2

selector = VarianceThreshold(threshold = 0.2)
X_selected = selector.fit_transform(X)

selected_columns = X.columns[selector.get_support()]

print("Selected Features:", list(selected_columns))

Selected Features: ['Age', 'Promoted', 'items']